/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface StakingInterface extends ethers.utils.Interface {
  functions: {
    "addAllowedToken(address,address)": FunctionFragment;
    "allowedTokens(uint256)": FunctionFragment;
    "contractEthBalance()": FunctionFragment;
    "getStakerIndex(address)": FunctionFragment;
    "getTokenValue(address)": FunctionFragment;
    "getUserSingleTokenUSDValue(address,address)": FunctionFragment;
    "getUserTotalUSDValue(address)": FunctionFragment;
    "isTokenAllowed(address)": FunctionFragment;
    "issueTokens()": FunctionFragment;
    "numberOfAllowedTokens()": FunctionFragment;
    "numberOfStakers()": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "rug()": FunctionFragment;
    "stakeTokens(address,uint256)": FunctionFragment;
    "stakers(uint256)": FunctionFragment;
    "stakingBalances(address,address)": FunctionFragment;
    "tokenPriceFeed(address)": FunctionFragment;
    "totalStakingRewards()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "uniqueTokensStaked(address)": FunctionFragment;
    "unstakeTokens(address,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "addAllowedToken",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "allowedTokens",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "contractEthBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getStakerIndex",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenValue",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserSingleTokenUSDValue",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserTotalUSDValue",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "isTokenAllowed",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "issueTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "numberOfAllowedTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "numberOfStakers",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "rug", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "stakeTokens",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stakers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stakingBalances",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenPriceFeed",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "totalStakingRewards",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "uniqueTokensStaked",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "unstakeTokens",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "addAllowedToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allowedTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contractEthBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStakerIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserSingleTokenUSDValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserTotalUSDValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isTokenAllowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "issueTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "numberOfAllowedTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "numberOfStakers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rug", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "stakeTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stakers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "stakingBalances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenPriceFeed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalStakingRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "uniqueTokensStaked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unstakeTokens",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
    "Received(address,uint256)": EventFragment;
    "StakeTokens(address,address)": EventFragment;
    "UnstakeTokens(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Received"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "StakeTokens"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UnstakeTokens"): EventFragment;
}

export type OwnershipTransferredEvent = TypedEvent<
  [string, string] & { previousOwner: string; newOwner: string }
>;

export type ReceivedEvent = TypedEvent<
  [string, BigNumber] & { arg0: string; arg1: BigNumber }
>;

export type StakeTokensEvent = TypedEvent<
  [string, string] & { tokenAddress: string; staker: string }
>;

export type UnstakeTokensEvent = TypedEvent<
  [string, string] & { tokenAddress: string; unstaker: string }
>;

export class Staking extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: StakingInterface;

  functions: {
    addAllowedToken(
      _tokenAddress: string,
      _oracleAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    allowedTokens(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    contractEthBalance(overrides?: CallOverrides): Promise<[BigNumber]>;

    getStakerIndex(
      _client: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getTokenValue(
      _tokenAddress: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber, number] & { price: BigNumber; decimals: number }>;

    getUserSingleTokenUSDValue(
      _user: string,
      _tokenAddress: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getUserTotalUSDValue(
      _user: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    isTokenAllowed(
      _tokenAddress: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    issueTokens(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    numberOfAllowedTokens(overrides?: CallOverrides): Promise<[BigNumber]>;

    numberOfStakers(overrides?: CallOverrides): Promise<[BigNumber]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    rug(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    stakeTokens(
      _tokenAddress: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    stakers(arg0: BigNumberish, overrides?: CallOverrides): Promise<[string]>;

    stakingBalances(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    tokenPriceFeed(arg0: string, overrides?: CallOverrides): Promise<[string]>;

    totalStakingRewards(overrides?: CallOverrides): Promise<[BigNumber]>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    uniqueTokensStaked(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    unstakeTokens(
      _tokenAddress: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  addAllowedToken(
    _tokenAddress: string,
    _oracleAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  allowedTokens(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  contractEthBalance(overrides?: CallOverrides): Promise<BigNumber>;

  getStakerIndex(
    _client: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getTokenValue(
    _tokenAddress: string,
    overrides?: CallOverrides
  ): Promise<[BigNumber, number] & { price: BigNumber; decimals: number }>;

  getUserSingleTokenUSDValue(
    _user: string,
    _tokenAddress: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getUserTotalUSDValue(
    _user: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  isTokenAllowed(
    _tokenAddress: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  issueTokens(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  numberOfAllowedTokens(overrides?: CallOverrides): Promise<BigNumber>;

  numberOfStakers(overrides?: CallOverrides): Promise<BigNumber>;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  rug(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  stakeTokens(
    _tokenAddress: string,
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  stakers(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  stakingBalances(
    arg0: string,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  tokenPriceFeed(arg0: string, overrides?: CallOverrides): Promise<string>;

  totalStakingRewards(overrides?: CallOverrides): Promise<BigNumber>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  uniqueTokensStaked(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  unstakeTokens(
    _tokenAddress: string,
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    addAllowedToken(
      _tokenAddress: string,
      _oracleAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    allowedTokens(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    contractEthBalance(overrides?: CallOverrides): Promise<BigNumber>;

    getStakerIndex(
      _client: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTokenValue(
      _tokenAddress: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber, number] & { price: BigNumber; decimals: number }>;

    getUserSingleTokenUSDValue(
      _user: string,
      _tokenAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getUserTotalUSDValue(
      _user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isTokenAllowed(
      _tokenAddress: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    issueTokens(overrides?: CallOverrides): Promise<void>;

    numberOfAllowedTokens(overrides?: CallOverrides): Promise<BigNumber>;

    numberOfStakers(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    rug(overrides?: CallOverrides): Promise<void>;

    stakeTokens(
      _tokenAddress: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    stakers(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    stakingBalances(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tokenPriceFeed(arg0: string, overrides?: CallOverrides): Promise<string>;

    totalStakingRewards(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    uniqueTokensStaked(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    unstakeTokens(
      _tokenAddress: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    "Received(address,uint256)"(
      undefined?: null,
      undefined?: null
    ): TypedEventFilter<[string, BigNumber], { arg0: string; arg1: BigNumber }>;

    Received(
      undefined?: null,
      undefined?: null
    ): TypedEventFilter<[string, BigNumber], { arg0: string; arg1: BigNumber }>;

    "StakeTokens(address,address)"(
      tokenAddress?: null,
      staker?: null
    ): TypedEventFilter<
      [string, string],
      { tokenAddress: string; staker: string }
    >;

    StakeTokens(
      tokenAddress?: null,
      staker?: null
    ): TypedEventFilter<
      [string, string],
      { tokenAddress: string; staker: string }
    >;

    "UnstakeTokens(address,address)"(
      tokenAddress?: null,
      unstaker?: null
    ): TypedEventFilter<
      [string, string],
      { tokenAddress: string; unstaker: string }
    >;

    UnstakeTokens(
      tokenAddress?: null,
      unstaker?: null
    ): TypedEventFilter<
      [string, string],
      { tokenAddress: string; unstaker: string }
    >;
  };

  estimateGas: {
    addAllowedToken(
      _tokenAddress: string,
      _oracleAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    allowedTokens(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    contractEthBalance(overrides?: CallOverrides): Promise<BigNumber>;

    getStakerIndex(
      _client: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTokenValue(
      _tokenAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getUserSingleTokenUSDValue(
      _user: string,
      _tokenAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getUserTotalUSDValue(
      _user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isTokenAllowed(
      _tokenAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    issueTokens(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    numberOfAllowedTokens(overrides?: CallOverrides): Promise<BigNumber>;

    numberOfStakers(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    rug(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    stakeTokens(
      _tokenAddress: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    stakers(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    stakingBalances(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tokenPriceFeed(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    totalStakingRewards(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    uniqueTokensStaked(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    unstakeTokens(
      _tokenAddress: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addAllowedToken(
      _tokenAddress: string,
      _oracleAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    allowedTokens(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    contractEthBalance(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getStakerIndex(
      _client: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTokenValue(
      _tokenAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getUserSingleTokenUSDValue(
      _user: string,
      _tokenAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getUserTotalUSDValue(
      _user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isTokenAllowed(
      _tokenAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    issueTokens(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    numberOfAllowedTokens(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    numberOfStakers(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    rug(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    stakeTokens(
      _tokenAddress: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    stakers(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    stakingBalances(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    tokenPriceFeed(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    totalStakingRewards(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    uniqueTokensStaked(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    unstakeTokens(
      _tokenAddress: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
